logging:
  level:
    root: info
    io.github.syakuis: trace
    org.springframework.web: debug
    org.springframework.security: trace
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: off
server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: spring-authorization-server
  main:
    banner-mode: console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authorization?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      max-lifetime: 600000
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    log-request-details: false
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2